# -- Theme Options --
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "light"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

disableImageOptimization = false
disableImageOptimizationMD = false
disableTextInHeader = false

highlightCurrentMenuArea = true
smartTOC = true

[header]
  layout = "fixed"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 12
  showMoreLink = true
  showMoreLinkDest = "posts"
  cardView = true

[article]
  showDate = true
  showViews = false
  showLikes = false
  showAuthor = false
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = true
  showTaxonomies = true
  showWordCount = false
  sharingLinks = ["linkedin", "email"]

[list]
  showHero = false
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showCards = true
  orderByWeight = false
  cardView = true

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showHero = false
  showBreadcrumbs = false
  cardView = true

[term]
  showHero = false
  showBreadcrumbs = false
  cardView = true
