# -- Theme Options --
# https://blowfish.page/docs/configuration/#theme-parameters

colorScheme = "blowfish"
defaultAppearance = "dark"
autoSwitchAppearance = false

enableSearch = true
enableCodeCopy = true

disableImageOptimization = true
disableImageOptimizationMD = true
disableTextInHeader = false

defaultBackgroundImage = "img/fireflies-custom.svg"

highlightCurrentMenuArea = true
smartTOC = true

[header]
  layout = "fixed-fill-blur"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = true
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "background"
  layoutBackgroundBlur = false
  showRecent = true
  showRecentItems = 999
  showMoreLink = false
  cardView = true

[article]
  showDate = true
  showViews = false
  showLikes = false
  showAuthor = false
  showHero = true
  heroStyle = "background"
  showBreadcrumbs = false
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = false
  showPagination = true
  showReadingTime = false
  showTableOfContents = true
  showRelatedContent = false
  relatedContentLimit = 9
  showTaxonomies = true
  showWordCount = false
  sharingLinks = ["linkedin", "email"]

[list]
  showHero = false
  showBreadcrumbs = false
  showSummary = false
  showTableOfContents = false
  showCards = true
  orderByWeight = false
  cardView = true

[sitemap]
  excludedKinds = []

[taxonomy]
  showTermCount = true
  showHero = false
  showBreadcrumbs = false
  cardView = true

[term]
  showHero = false
  showBreadcrumbs = false
  cardView = true
